name: Python application

on:
  push:
    branches: 
      - "main"
      - "**"  # Isto captura todas as branches
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Conventional Commit Checker for Pull Requests
        if: github.event_name == 'pull_request'
        uses: agenthunt/conventional-commit-checker-action@v2.0.0

      - name: Conventional Commit Checker for Push Events
        if: github.event_name == 'push'
        run: |
          # Checks the latest commit message for conventional format
          last_commit_message=$(git log -1 --pretty=%B)
          echo "Last commit message: $last_commit_message"
          # Define a regex for conventional commits
          regex="^(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: .+$"
          if [[ ! $last_commit_message =~ $regex ]]; then
            echo "Commit message does not follow Conventional Commits format."
            exit 1
          fi

      - name: Test with pytest
        run: |
          main
